[package]
name = "gnome-who"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false
exclude = ["screenshot.png"]

[dependencies]
anyhow = "1.0.26"
chrono = "0.4.19"
glib = "0.10.0"
gtk = "0.9.0"
inotify = "0.9.2"
libappindicator = "0.5.2"
libc = "0.2.86"
mio = { version = "0.7.7", features = ["os-poll"] }
mio-pidfd = "0.2.0"
nix = "0.19.1"
once_cell = "1.3.1"
tempfile = "3.1.0"
utmp-rs = "0.1.1"

[patch.crates-io.mio-pidfd]
path = "./mio-pidfd"
