[package]
name = "gnome-who"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false
exclude = ["screenshot.png"]

[dependencies]
anyhow = "1.0.26"
glib = "0.9.2"
gtk = "0.8.1"
inotify = "0.8.2"
libappindicator = "0.5.1"
once_cell = "1.3.1"
utmp-rs = "0.1.1"
tempfile = "3.1.0"
